#!/bin/bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

SRC_BRANCH="ad.lan.v${1}"

# 将错误信息用红色打印
echoError() {
    echo -e "\033[31mError: ${1} \033[0m"
}

# 同步远程仓库
if ! git fetch --all --tags --prune; then
    echoError "git fetch failed!"
    exit 1
fi

# 内网对应版本的tag必须已经存在
if [ $(git ls-remote --tags origin | grep -E "refs/tags/${SRC_BRANCH}$|refs/heads/${SRC_BRANCH}$" | wc -l) -eq 0 ]; then
    echoError "tag ${SRC_BRANCH} does not exist!"
    exit 1
fi

# 检查是否还有未提交的代码
if [ $(git status -s | wc -l) -ne 0 ]; then
    echoError "code not committed!"
    git status
    exit 1
fi

# 切换到内网tag
git checkout ${SRC_BRANCH}

IFS_OLD=$IFS
IFS=$'\n'
date
for line in $(cat ${DIR}/assets/yhchannel.txt)
do
{
    CHANNEL_NAME=$(echo $line|awk '{print $1}')
    VERSOIN_INFO[0]=$(echo $line|awk '{print $2}')
    VERSOIN_INFO[1]=$(echo $line|awk '{print $3}')
    VERSOIN_INFO[2]=$(echo $line|awk '{print $4}')

    echo $line
    sh ${DIR}/release_common_git_noswich.sh ${VERSOIN_INFO[0]} ${VERSOIN_INFO[1]} ${VERSOIN_INFO[2]} ${CHANNEL_NAME} assets/upload_yh.py
    #sleep 5
}&
done
wait
date
IFS=$IFS_OLD

python ${DIR}/assets/upload_yh.py
